mirror:
  image:
    name: alpine/git:latest
    entrypoint: [""]
  script:
    - git fetch origin main:staging
    - git checkout staging
    - git merge main
    - git push origin staging
  only:
    - main
