sync staging with main:
  image:
    name: alpine/git:latest
    entrypoint: [""]
  script:
    - git config --global user.email "maintainer@pr-mebel.ru"
    - git config --global user.name "Maintainer PrMebel"
    - git fetch origin
    - git checkout staging
    - git merge --commit --no-edit main
    - git push origin staging
  only:
    - main
