image: node:16

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

stages:
  - lint
  - merge

lint:
  stage: lint
  script:
    - if [[ "$CI_COMMIT_REF_NAME" != "main" && "$CI_COMMIT_REF_NAME" != "staging" ]]; then
        yarn;
        yarn lint;
        yarn typecheck;
      fi

merge_to_staging:
  stage: merge
  only:
    - main
  script:
    - git checkout staging
    - git merge main
    - git push origin staging
