image: node:16

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

stages:
  - lint
  - mirror

lint:
  stage: lint
  script:
    - if [[ "$CI_COMMIT_REF_NAME" != "main" && "$CI_COMMIT_REF_NAME" != "staging" ]]; then
        yarn;
        yarn lint;
        yarn typecheck;
      fi

mirror:
  stage: mirror
  image: alpine/git
  script:
    - apk add --no-cache openssh-client
    - git fetch origin main:staging
  only:
    - main
