image: node:16

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
    paths:
        - node_modules/

lint:
    script:
        - yarn
        - yarn lint
        - yarn typecheck
