sync staging with main:
  image:
    name: alpine/git:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: fetch
  script:
    - git config --global user.email "maintainer@pr-mebel.ru"
    - git config --global user.name "Maintainer PrMebel"
    - echo "Setting up GitLab PAT"
    - |
      git remote set-url origin \
        "https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git"
    - git fetch origin
    - git checkout staging
    - git rebase origin/main
    - git push --force origin staging
  only:
    - main
