# .github/workflows/deploy.yml (Rename if desired)
name: Build and Deploy Next.js to VPS

on:
  push:
    branches:
      - main # Trigger deployment on push to main branch

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-latest # Use GitHub-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your Node.js LTS version
          cache: 'npm' # Cache npm dependencies

      - name: Install Dependencies
        run: npm ci # Use clean install (installs devDependencies needed for build)

      - name: Build Application
        run: npm run build
        env:
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_URI: ${{ secrets.CONTENTFUL_URI }}
          EMAIL_MAIL_RU: ${{ secrets.EMAIL_MAIL_RU }}
          PASSWORD_MAIL_RU: ${{ secrets.PASSWORD_MAIL_RU }}
          ROISTAT_KEY: ${{ secrets.ROISTAT_KEY }}

      - name: Prepare Artifact Directory
        run: |
          # Create a directory to hold deployment files
          mkdir deployment
          # Copy necessary files into the deployment directory
          cp -R .next ./deployment/
          cp -R public ./deployment/
          cp package.json ./deployment/
          cp package-lock.json ./deployment/
          cp next.config.js ./deployment/
          cp ecosystem.config.js ./deployment/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build-artifact
          path: ./deployment/ # Upload the prepared directory

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build-artifact

      - name: Copy files to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          source: './*' # Copy contents of deployment dir
          target: ${{ secrets.DEPLOY_PATH }}

      - name: Execute deployment commands on VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          script: |
            # Navigate to deployment directory
            echo "Navigating to ${{ secrets.DEPLOY_PATH }}"
            cd ${{ secrets.DEPLOY_PATH }}

            # Source NVM (Still needed for npm ci)
            echo "Sourcing NVM..."
            source $HOME/.nvm/nvm.sh
            echo "Node version: $(node -v), npm version: $(npm -v)"

            # Create .env file from secrets
            echo "Creating .env.production.local file..."
            # ... (echo commands for your env vars) ...
            chmod 600 .env.production.local
            echo ".env file created."

            # Install ONLY production dependencies
            echo "Installing production dependencies..."
            npm ci

            echo "Restarting/Starting application '${{ secrets.APP_NAME }}' via ecosystem file..."
            # Ensure ecosystem file is present (should be copied by SCP)
            sudo ${{ secrets.PM2_PATH }} startOrRestart ecosystem.config.js
            sudo ${{ secrets.PM2_PATH }} save

            echo "Deployment finished successfully!"
