# .github/workflows/deploy-via-pull.yml
name: Deploy Next.js to VPS via Git Pull

on:
  push:
    branches:
      - main # Trigger deployment on push to main branch

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest # Only need a runner to execute the SSH command

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT || 22 }}
          script: |
            # Navigate to deployment directory
            echo "Navigating to ${{ secrets.DEPLOY_PATH }}"
            cd ${{ secrets.DEPLOY_PATH }}

            # Source NVM to make node and npm available
            echo "Sourcing NVM..."
            # Adjust path if your nvm directory is different
            source $HOME/.nvm/nvm.sh
            echo "Node version: $(node -v), npm version: $(npm -v)" # Verify NVM loaded

            # Ensure we are on the correct branch (optional but good practice)
            echo "Checking out main branch..."
            git checkout main
            git reset --hard origin/main # Discard local changes, match remote

            # Pull latest changes using the deploy key configured on the VPS
            echo "Pulling latest changes from GitHub..."
            git pull origin main

            # Create .env file from secrets
            echo "Creating .env.production.local file..."
            # ... (rest of echo commands for .env) ...
            chmod 600 .env.production.local
            echo ".env file created."

            # Install ALL dependencies (including devDependencies)
            echo "Installing dependencies..."
            npm ci # Installs based on package-lock.json

            # Build the application ON THE SERVER
            echo "Building application..."
            npm run build

            # Reload/Start application using PM2
            echo "Restarting/Starting application '${{ secrets.APP_NAME }}' with PM2..."
            # ... (your pm2 restart || start command) ...
            sudo ${{ secrets.PM2_PATH }} restart ${{ secrets.APP_NAME }} || sudo ${{ secrets.PM2_PATH }} start npm --name "${{ secrets.APP_NAME }}" -- start
            sudo ${{ secrets.PM2_PATH }} save # Save process list

            echo "Deployment finished successfully!"
